### ISSUE TITLE
Issue since 3.6.5

### ISSUE THREAD

**Issue by halfluck** [cmroche/OctoPrint-HomeAssistant#110]
Since the latest update my HA instance has been spewing gigabytes and gigabytes of errors as below:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state
    raise ValueError(
ValueError: Sensor sensor.printer1_print_time_left has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '3:52:25' (<class 'str'>)
2023-07-18 11:19:12.100 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.printer1_print_time, topic: 'octoPrint1/hass/printing' with payload: b'{"state": {"text": "Printing", "flags": {"operational": true, "printing": true, "cancelling": false, "pausing": false, "resuming": false, "finishing": false, "closedOrError": false, "error": false, "paused": false, "ready": false, "sdReady": true}, "error": ""}, "job": {"file": {"name": "MONSTERS MINI CUTTERS COMPLETE FLIPPED_0.2mm_PLA_MK3S_4h15m.gcode", "path": "MONSTERS MINI CUTTERS COMPLETE FLIPPED_0.2mm_PLA_MK3S_4h15m.gcode", "display": "MONSTERS MINI CUTTERS COMPLETE FLIPPED_0.2mm_PLA_MK3S_4h15m.gcode", "origin": "local", "size": 6884046, "date": 1689648424}, "estimatedPrintTime": null, "averagePrintTime": null, "lastPrintTime": null, "filament": null, "user": "admin", "estimatedPrintTimeFormatted": null}, "currentZ": 0.8, "progress": {"completion": 11.784334387074114, "filepos": 811239, "printTime": 1927, "printTimeLeft": 13945, "printTimeLeftOrigin": "estimate", "printTimeLeftFormatted": "3:52:25", "printTimeFormatted": "0:32:07"}, "offsets": {}, "resends": {"count": 0, "transmitted": 4059165, "ratio": 0}, "_timestamp": 1689650351}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0:32:07'

**Comment by mreditor97** [comment]
Your problem is fixed in #108. If you could install it on your system to try it out, that would be great!

**Comment by halfluck** [comment]
Thanks so much I can confirm your patch fixes my issue :)
